spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server1
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false